services:
  python-service:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile  # Optional if your file is named "Dockerfile"
    command: python3 -m http.server 1234
    #image: python-with-dependencies:3.13.5-bookworm
    ports:
      - "1234:1234"  # optional, map host:container ports
    volumes:
      - .:/covid-data       # optional, bind mount current dir
    #environment:
    #  - ENV_VAR_NAME=value  # optional env variables
  