default_language_version:
    python: python3.12
exclude: devcontainer.json|__init__.py
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-ast  # Basic Python syntax check
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length=88"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]  # Example: add stubs if needed

  #- repo: https://github.com/pycqa/pylint
  #  rev: v3.3.4
  #  hooks:
  #    - id: pylint
  #      language: python
  #      additional_dependencies:
    #      - pandas
    #      - requests
    #      - tqdm
    #      - dotenv
    #      - ijson
    #      - sqlalchemy
    #      - thefuzz
  #        - apache-airflow
  #        - pylint-airflow
    #    args: ["--generated-members=pandas.*"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile","black"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-r", "./"]  # Recursively scan for security issues
