services:
  python:
    container_name: python-covid-data
    build:
      context: ../../
      dockerfile: Dockerfile.python
    volumes:
      - ../../:/covid-data:cached
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    container_name: postgres
    image: postgres:16-alpine
    hostname: postgres-covid
    restart: unless-stopped
    env_file:
      - ../../.env-dev
    ports:
      - '54001:5432'
    volumes:
      - ../../.db:/var/lib/postgresql/data
      - ../init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin-covid
    image: dpage/pgadmin4:9.7
    restart: unless-stopped
    env_file:
      - ../../.env-dev
    ports:
      - '54002:80'
    depends_on:
      postgresdb:
        condition: service_healthy
