#!/bin/bash
set -e

echo $POSTGRES_USER
echo $POSTGRES_DB
echo $AIRFLOW_DB
echo $AIRFLOW_DB_USER
echo $AIRFLOW_DB_PW

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $AIRFLOW_DB_USER WITH PASSWORD '$AIRFLOW_DB_PW';
    CREATE DATABASE $AIRFLOW_DB;
    GRANT ALL PRIVILEGES ON DATABASE $AIRFLOW_DB TO $AIRFLOW_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$AIRFLOW_DB" <<-EOSQL
    GRANT ALL ON SCHEMA public TO $AIRFLOW_DB_USER;
EOSQL
