--dim_date
CREATE TABLE IF NOT EXISTS dim_date
(
    "dim_date_key"      INT                     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date"              DATE,
    "year"              INT,
    "month"             INT,
    "month_name"        VARCHAR(10),
    "day"               INT,
    "day_name"          VARCHAR(10),
    "week"              INT,
    "start_of_week"     BOOLEAN,
    "end_of_week"       BOOLEAN,
    "created_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    "updated_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("date")
);
--#
--dim_date default
INSERT INTO dim_date ("dim_date_key","date","year","month","month_name","day","day_name","week","start_of_week","end_of_week")
VALUES (-1,'1900-01-01',0,0,'-unknown-',0,'-unknown-',0,false,false);
