--dim_date
CREATE TABLE IF NOT EXISTS dim_date
(
    "dim_date_key"      INT                     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date"              DATE,
    "year"              INT,
    "month"             INT,
    "month_name"        VARCHAR(10),
    "day"               INT,
    "day_name"          VARCHAR(10),
    "week"              INT,
    "start_of_week"     BOOLEAN,
    "end_of_week"       BOOLEAN,
    "created_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    "updated_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("date")
);
--#
--dim_date default
INSERT INTO dim_date ("dim_date_key","date","year","month","month_name","day","day_name","week","start_of_week","end_of_week")
VALUES (-1,'1900-01-01',0,0,'-unknown-',0,'-unknown-',0,false,false);
--#
--dim_week_start_date view
CREATE OR REPLACE VIEW "dim_week_start_date" AS (SELECT
    "dim_date_key"   AS "dim_week_start_date_key",
    "date"           AS "week_start_date",
    "year"           AS "week_start_date_year",
    "month"          AS "week_start_date_month",
    "month_name"     AS "week_start_date_month_name",
    "day"            AS "week_start_date_day",
    "day_name"       AS "week_start_date_day_name",
    "week"           AS "week_start_date_week",
    "start_of_week"  AS "week_start_date_start_of_week",
    "end_of_week"    AS "week_start_date_end_of_week",
    "created_ts"     AS "week_start_date_created_ts",
    "updated_ts"     AS "week_start_date_updated_ts"
    FROM "dim_date");
--#
--dim_week_end_date view
CREATE OR REPLACE VIEW "dim_week_end_date" AS (SELECT
    "dim_date_key"   AS "dim_week_end_date_key",
    "date"           AS "week_end_date",
    "year"           AS "week_end_date_year",
    "month"          AS "week_end_date_month",
    "month_name"     AS "week_end_date_month_name",
    "day"            AS "week_end_date_day",
    "day_name"       AS "week_end_date_day_name",
    "week"           AS "week_end_date_week",
    "start_of_week"  AS "week_end_date_start_of_week",
    "end_of_week"    AS "week_end_date_end_of_week",
    "created_ts"     AS "week_end_date_created_ts",
    "updated_ts"     AS "week_end_date_updated_ts"
    FROM "dim_date");
