--dim_country
CREATE TABLE IF NOT EXISTS dim_country
(
    "dim_country_key"   INT                     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "country_code"      VARCHAR(10),
    "country_name"      VARCHAR(255),
    "territory_code"    VARCHAR(10),
    "continent"         VARCHAR(255),
    "created_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    "updated_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("country_code")
);
--#
--dim_country default
INSERT INTO dim_country ("dim_country_key","country_code","country_name","territory_code","continent")
VALUES (-1,'--','-unknown-','---','-unknown-');
--#
--dim_region
CREATE TABLE IF NOT EXISTS dim_region
(
    "dim_region_key"    INT                     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "region_code"       VARCHAR(10),
    "region_name"       VARCHAR(255),
    "created_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    "updated_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("region_code")
);
--#
--dim_region default
INSERT INTO dim_region ("dim_region_key","region_code","region_name")
VALUES (-1,'--','-unknown-');
--#
--dim_vaccine
CREATE TABLE IF NOT EXISTS dim_vaccine
(
    "dim_vaccine_key"   INT                     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vaccine_code"      VARCHAR(20),
    "vaccine_name"      VARCHAR(255),
    "created_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    "updated_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("vaccine_code")
);
--#
--dim_vaccine default
INSERT INTO dim_vaccine ("dim_vaccine_key","vaccine_code","vaccine_name")
VALUES (-1,'--','-unknown-');
--#
--dim_source
CREATE TABLE IF NOT EXISTS dim_source
(
    "dim_source_key"    INT                     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "source_name"       VARCHAR(255),
    "created_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    "updated_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("source_name")
);
--#
--dim_source default
INSERT INTO dim_source ("dim_source_key","source_name")
VALUES (-1,'-unknown-');
--#
--dim_status
CREATE TABLE IF NOT EXISTS dim_status
(
    "dim_status_key"        INT                 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "colour_name"           VARCHAR(255),
    "colour_description"    VARCHAR(255),
    "created_ts"            TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
    "updated_ts"            TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("colour_name", "colour_description")
);
--#
--dim_status default
INSERT INTO dim_status ("dim_status_key","colour_name","colour_description")
VALUES (-1,'-unknown-','-unknown-');
--#
--dim_age
CREATE TABLE IF NOT EXISTS dim_age
(
    "dim_age_key"       INT                     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "age_group"         VARCHAR(255),
    "age_lower_limit"   INT,
    "age_upper_limit"   INT,
    "created_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    "updated_ts"        TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("age_group")
);
--#
--dim_status default
INSERT INTO dim_age ("dim_age_key","age_group","age_lower_limit","age_upper_limit")
VALUES (-1,'-unknown-',0,0);
--#
--fact_vaccine_tracker_country
CREATE TABLE IF NOT EXISTS fact_vaccine_tracker_country
(
    "dim_date_key"              INT             NOT NULL    REFERENCES dim_date(dim_date_key),
    "dim_country_key"           INT             NOT NULL    REFERENCES dim_country(dim_country_key),
    "dim_vaccine_key"           INT             NOT NULL    REFERENCES dim_vaccine(dim_vaccine_key),
    "dim_source_key"            INT             NOT NULL    REFERENCES dim_source(dim_source_key),
    "dim_age_key"               INT             NOT NULL    REFERENCES dim_age(dim_age_key),
    "first_dose"                INT             NOT NULL,
    "first_dose_refused"        INT             NOT NULL,
    "second_dose"               INT             NOT NULL,
    "additional_dose_1"         INT             NOT NULL,
    "additional_dose_2"         INT             NOT NULL,
    "additional_dose_3"         INT             NOT NULL,
    "additional_dose_4"         INT             NOT NULL,
    "additional_dose_5"         INT             NOT NULL,
    "unknown_dose"              INT             NOT NULL,
    "doses_received"            INT             NOT NULL,
    "doses_exported"            INT             NOT NULL,
    "population"                INT             NOT NULL,
    "denominator"               INT             NOT NULL,
    "created_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    "updated_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    UNIQUE("dim_date_key", "dim_country_key", "dim_vaccine_key", "dim_source_key", "dim_age_key")
);
--#
--fact_vaccine_tracker_region
CREATE TABLE IF NOT EXISTS fact_vaccine_tracker_region
(
    "dim_date_key"              INT             NOT NULL    REFERENCES dim_date(dim_date_key),
    "dim_country_key"           INT             NOT NULL    REFERENCES dim_country(dim_country_key),
    "dim_region_key"            INT             NOT NULL    REFERENCES dim_region(dim_region_key),
    "dim_vaccine_key"           INT             NOT NULL    REFERENCES dim_vaccine(dim_vaccine_key),
    "dim_source_key"            INT             NOT NULL    REFERENCES dim_source(dim_source_key),
    "dim_age_key"               INT             NOT NULL    REFERENCES dim_age(dim_age_key),
    "first_dose"                INT             NOT NULL,
    "first_dose_refused"        INT             NOT NULL,
    "second_dose"               INT             NOT NULL,
    "additional_dose_1"         INT             NOT NULL,
    "additional_dose_2"         INT             NOT NULL,
    "additional_dose_3"         INT             NOT NULL,
    "additional_dose_4"         INT             NOT NULL,
    "additional_dose_5"         INT             NOT NULL,
    "unknown_dose"              INT             NOT NULL,
    "doses_received"            INT             NOT NULL,
    "doses_exported"            INT             NOT NULL,
    "population"                INT             NOT NULL,
    "denominator"               INT             NOT NULL,
    "created_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    "updated_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    UNIQUE("dim_date_key", "dim_country_key", "dim_region_key", "dim_vaccine_key", "dim_source_key", "dim_age_key")
);
--#
--fact_movement_indicators_country
CREATE TABLE IF NOT EXISTS fact_movement_indicators_country
(
    "dim_week_start_date_key"   INT             NOT NULL    REFERENCES dim_date(dim_date_key),
    "dim_week_end_date_key"     INT             NOT NULL    REFERENCES dim_date(dim_date_key),
    "dim_country_key"           INT             NOT NULL    REFERENCES dim_country(dim_country_key),
    "dim_status_key"            INT             NOT NULL    REFERENCES dim_status(dim_status_key),
    "population"                INT             NOT NULL,
    "new_cases_last_7days"      INT             NOT NULL,
    "new_cases_last_14days"     INT             NOT NULL,
    "notification_rate"         NUMERIC(10,5)   NOT NULL,
    "testing_rate"              NUMERIC(10,5)   NOT NULL,
    "positivity_rate"           NUMERIC(10,5)   NOT NULL,
    "vaccination_rate"          NUMERIC(10,5)   NOT NULL,
    "created_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    "updated_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    UNIQUE("dim_week_start_date_key", "dim_week_end_date_key", "dim_country_key", "dim_status_key")
);
--#
--fact_movement_indicators_region
CREATE TABLE IF NOT EXISTS fact_movement_indicators_region
(
    "dim_week_start_date_key"   INT             NOT NULL    REFERENCES dim_date(dim_date_key),
    "dim_week_end_date_key"     INT             NOT NULL    REFERENCES dim_date(dim_date_key),
    "dim_country_key"           INT             NOT NULL    REFERENCES dim_country(dim_country_key),
    "dim_region_key"            INT             NOT NULL    REFERENCES dim_region(dim_region_key),
    "dim_status_key"            INT             NOT NULL    REFERENCES dim_status(dim_status_key),
    "population"                INT             NOT NULL,
    "new_cases_last_7days"      INT             NOT NULL,
    "new_cases_last_14days"     INT             NOT NULL,
    "notification_rate"         NUMERIC(10,5)   NOT NULL,
    "testing_rate"              NUMERIC(10,5)   NOT NULL,
    "positivity_rate"           NUMERIC(10,5)   NOT NULL,
    "vaccination_rate"          NUMERIC(10,5)   NOT NULL,
    "positivity_rate_combined"  NUMERIC(10,5)   NOT NULL,
    "testing_rate_combined"     NUMERIC(10,5)   NOT NULL,
    "created_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    "updated_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    UNIQUE("dim_week_start_date_key", "dim_week_end_date_key", "dim_country_key", "dim_region_key", "dim_status_key")
);
--#
--fact_cases_deaths_country_daily
CREATE TABLE IF NOT EXISTS fact_cases_deaths_country_daily
(
    "dim_date_key"              INT             NOT NULL    REFERENCES dim_date(dim_date_key),
    "dim_country_key"           INT             NOT NULL    REFERENCES dim_country(dim_country_key),
    "cases"                     INT             NOT NULL,
    "cases_cumulative"          INT             NOT NULL,
    "cases_notification_rate"   NUMERIC(10,5)   NOT NULL,
    "deaths"                    INT             NOT NULL,
    "deaths_cumulative"         INT             NOT NULL,
    "deaths_notification_rate"  NUMERIC(10,5)   NOT NULL,
    "population"                INT             NOT NULL,
    "created_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    "updated_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    UNIQUE("dim_date_key", "dim_country_key")
);
--#
--fact_cases_deaths_country_weekly
CREATE TABLE IF NOT EXISTS fact_cases_deaths_country_weekly
(
    "dim_week_start_date_key"   INT             NOT NULL    REFERENCES dim_date(dim_date_key),
    "dim_week_end_date_key"     INT             NOT NULL    REFERENCES dim_date(dim_date_key),
    "dim_country_key"           INT             NOT NULL    REFERENCES dim_country(dim_country_key),
    "cases"                     INT             NOT NULL,
    "cases_cumulative"          INT             NOT NULL,
    "cases_notification_rate"   NUMERIC(10,5)   NOT NULL,
    "deaths"                    INT             NOT NULL,
    "deaths_cumulative"         INT             NOT NULL,
    "deaths_notification_rate"  NUMERIC(10,5)   NOT NULL,
    "created_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    "updated_ts"                TIMESTAMP       DEFAULT     CURRENT_TIMESTAMP,
    UNIQUE("dim_week_start_date_key", "dim_week_end_date_key", "dim_country_key")
);
